#!/bin/sh
# Runs the Ruby lintus from this checkout, honouring $JEV_API_URL. Used to check
# the conformance suite against the Ruby implementation:
#
#   LINTUS_BIN=test/support/lintus-ruby cargo test --test conformance
root=$(cd "$(dirname "$0")/../.." && pwd)
RUBYOPT="-I$root/lib -r$root/test/support/jev_api_url.rb $RUBYOPT" exec ruby "$root/exe/lintus" "$@"
